//
// Created by kolya on 18.11.2023.
//

#ifndef CLIENTSERVERHELPER_H
#define CLIENTSERVERHELPER_H

#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 60006
#define SERVER_MSG_PREFIX "[SERVER]: "
#define SERVER_ERROR_MSG_PREFIX "[SERERR]: "

#define BUFFER_SIZE 1024

#define CLIENT_MSG_PREFIX "[CLIENT]: "
#define CLIENT_ERROR_MSG_PREFIX "[CLIERR]: "
#define CLIENT_MESSAGE_DELIMITER '#'

#endif //CLIENTSERVERHELPER_H
